# Run this suite to test the rest of the suites.

tests:
    example 1:
        command: ./commander test example-1.yaml
        exit-code: 0
    ls test 1:
        command: ./commander test ls-test-1.yaml
        exit-code: 0
    ls test 2:
        command: ./commander test ls-test-2.yaml
        exit-code: 0
    ls test 3:
        command: ./commander test ls-test-3.yaml
        exit-code: 0

